version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
    ports:
      - "3005:3000"
    networks:
      - common-network
    env_file:
      - .env
  mysql-container:
    image: mysql
    volumes:
      - /Reggie/fluffycx/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: reggie
      MYSQL_ROOT_PASSWORD: 1234567890
    networks:
      - common-network
    ports:
      - "3307:3307"
networks:
  common-network:
    driver: bridge