version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
    ports:
      - "3005:3005"
    networks:
      - common-network
    env_file:
      - .env
  mysql-container:
    image: mysql
    volumes:
      - / your mysql docker container volumes path
    environment:
      MYSQL_DATABASE: reggie
      MYSQL_ROOT_PASSWORD: your password
    networks:
      - common-network
    ports:
      - "3307:3307"
networks:
  common-network:
    driver: bridge
